### ISSUE TITLE
couldn't find DSO to load: libv8executor.so

### ISSUE THREAD

**Issue by mars-lan** [Kudo/react-native-v8#33]
Similar to https://github.com/Kudo/react-native-v8/issues/29 but with a different stacktrace.

```
Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libv8executor.so
com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:738)
com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:591)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:529)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:484)
com.facebook.v8.reactexecutor.V8Executor.<clinit> (V8Executor.java:16)
com.facebook.v8.reactexecutor.V8ExecutorFactory.create (V8ExecutorFactory.java:17)
com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java:952)
java.lang.Thread.run (Thread.java:818)
```

Using 
react-native `0.61.5`
react-native-v8 `0.61.4-patch.1`
v8-android-intl `7.8.1`

**Comment by Kudo** [comment]
@mars-lan Could you help to unzip your apk and double check if libv8executor.so existed or not?
On the other hand, please share more log, probably the part before this exception which is helpful for troubleshooting.

I also published react-native-v8@0.61.5-patch.0 yesterday. Please use the version paired with RN 0.61.5 to reduce risk.
Thank you.

**Comment by mars-lan** [comment]
Seems like libv8executor.so exists for all architectures

```
$ $ unzip -l XXX.apk | grep -E "lib(fb|v8executor|c\+\+)"
   977256  00-00-1980 00:00   lib/arm64-v8a/libc++_shared.so
   174296  00-00-1980 00:00   lib/arm64-v8a/libfb.so
   342168  00-00-1980 00:00   lib/arm64-v8a/libv8executor.so
   575328  00-00-1980 00:00   lib/armeabi-v7a/libc++_shared.so
   140976  00-00-1980 00:00   lib/armeabi-v7a/libfb.so
   280284  00-00-1980 00:00   lib/armeabi-v7a/libv8executor.so
   997224  00-00-1980 00:00   lib/x86/libc++_shared.so
   165648  00-00-1980 00:00   lib/x86/libfb.so
   337648  00-00-1980 00:00   lib/x86/libv8executor.so
  1038968  00-00-1980 00:00   lib/x86_64/libc++_shared.so
   174568  00-00-1980 00:00   lib/x86_64/libfb.so
   358824  00-00-1980 00:00   lib/x86_64/libv8executor.so
```

It still crashes consistently on emulator after updating to react-native-v8@0.61.5-patch.0 with the following stacktrace, which seems to suggest a problem loading `libc++_shared.so` & `libfb.so`

```
2019-11-29 07:56:04.346 6274-6274/? I/GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
2019-11-29 07:56:04.375 6274-6274/? I/GoogleInputMethod: onStartInput() : Dummy InputConnection bound
2019-11-29 07:56:04.380 16243-16342/com.invisatime W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.invisatime/lib-main/libc++_shared.so" has unexpected e_machine: 40 (EM_ARM)
2019-11-29 07:56:04.384 16243-16342/com.invisatime W/System.err:     at java.lang.Runtime.load0(Runtime.java:928)
2019-11-29 07:56:04.384 16243-16342/com.invisatime W/System.err:     at java.lang.System.load(System.java:1633)
2019-11-29 07:56:04.384 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:393)
2019-11-29 07:56:04.384 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
2019-11-29 07:56:04.385 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
2019-11-29 07:56:04.385 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
2019-11-29 07:56:04.385 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.386 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
2019-11-29 07:56:04.386 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
2019-11-29 07:56:04.386 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
2019-11-29 07:56:04.386 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
2019-11-29 07:56:04.386 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
2019-11-29 07:56:04.386 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.386 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.v8.reactexecutor.V8Executor.<clinit>(V8Executor.java:16)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.v8.reactexecutor.V8ExecutorFactory.create(V8ExecutorFactory.java:17)
2019-11-29 07:56:04.387 16243-16342/com.invisatime W/System.err:     at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-11-29 07:56:04.388 16243-16342/com.invisatime E/SoLoader: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.invisatime/lib-main/libc++_shared.so" has unexpected e_machine: 40 (EM_ARM)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err: com.facebook.soloader.SoLoader$WrongAbiError: APK was built for a different platform
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:645)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
2019-11-29 07:56:04.388 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at com.facebook.v8.reactexecutor.V8Executor.<clinit>(V8Executor.java:16)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at com.facebook.v8.reactexecutor.V8ExecutorFactory.create(V8ExecutorFactory.java:17)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err: Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.invisatime/lib-main/libc++_shared.so" has unexpected e_machine: 40 (EM_ARM)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err: 	... 18 more
2019-11-29 07:56:04.389 16243-16342/com.invisatime E/SoLoader: couldn't find DSO to load: libfb.so caused by: APK was built for a different platform
2019-11-29 07:56:04.389 16243-16342/com.invisatime W/System.err: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfb.so caused by: APK was built for a different platform
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
2019-11-29 07:56:04.390 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
2019-11-29 07:56:04.391 16243-16342/com.invisatime W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
2019-11-29 07:56:04.391 16243-16342/com.invisatime W/System.err:     at com.facebook.v8.reactexecutor.V8Executor.<clinit>(V8Executor.java:16)
2019-11-29 07:56:04.391 16243-16342/com.invisatime W/System.err:     at com.facebook.v8.reactexecutor.V8ExecutorFactory.create(V8ExecutorFactory.java:17)
2019-11-29 07:56:04.391 16243-16342/com.invisatime W/System.err:     at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
2019-11-29 07:56:04.391 16243-16342/com.invisatime W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-11-29 07:56:04.391 16243-16342/com.invisatime E/SoLoader: couldn't find DSO to load: libv8executor.so caused by: couldn't find DSO to load: libfb.so caused by: APK was built for a different platform
2019-11-29 07:56:04.392 16243-16342/com.invisatime E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.invisatime, PID: 16243
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libv8executor.so caused by: couldn't find DSO to load: libfb.so caused by: APK was built for a different platform
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.facebook.v8.reactexecutor.V8Executor.<clinit>(V8Executor.java:16)
        at com.facebook.v8.reactexecutor.V8ExecutorFactory.create(V8ExecutorFactory.java:17)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by Kudo** [comment]
@mars-lan From the log, it is getting a little wield to me.
It seems the system try to load library from `/data/data/com.invisatime/lib-main/libc++_shared.so` and the library is built for arm. Assuming you were ran on x64 emulator and not able to load arm based library.

Did you ever try reinstall your app or cleanup app data which to remove files from `/data/data/com.invisatime/`?

Otherwise, please try to unzip your apk the use `file` to verify the library platform.
```sh
$ mkdir /tmp/foo && cd /tmp/foo && unzip /path/to/XXX.apk
$ file lib/x86_64/libc++_shared.so
lib/x86_64/libc++_shared.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7779489e2e0b2b093fd3386d87c28afdbf6ca63a, stripped
$ file lib/x86_64/libfb.so                                                                                                                                                                     
lib/x86_64/libfb.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5b9bfbac6a6dbf6fa3b245012d913296d5064443, stripped
```

**Comment by mars-lan** [comment]
Looks like this is most likely a bug in `soloader 0.8.0`: https://github.com/facebook/SoLoader/issues/55 and has nothing to do with `react-native-v8`. Closing this issue.

**Comment by zyestin** [comment]
same issue as below. `cd android && ./gradlew clean && cd ..` will work, then exucte `run-android`, everything goes well.
```
2023-10-23 20:23:38.065 30587-30587/com.myApp D/ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
2023-10-23 20:23:38.065 30587-30587/com.myApp D/ReactNative: ReactInstanceManager.recreateReactContextInBackground()
2023-10-23 20:23:38.066 30587-30587/com.myApp D/ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
2023-10-23 20:23:38.067 30587-30675/com.myApp D/SoLoader: About to load: libv8executor.so
2023-10-23 20:23:38.067 30587-30675/com.myApp D/SoLoader: libv8executor.so not found on /data/data/com.myApp/lib-main
2023-10-23 20:23:38.067 30587-30675/com.myApp D/SoLoader: libv8executor.so not found on /data/app/com.myApp-YmzXmLHzJPnhwWqk0O3EtA==/lib/arm64
2023-10-23 20:23:38.067 30587-30675/com.myApp D/SoLoader: libv8executor.so not found on /vendor/lib64
2023-10-23 20:23:38.067 30587-30675/com.myApp D/SoLoader: libv8executor.so not found on /system/lib64
2023-10-23 20:23:38.069 30587-30675/com.myApp E/SoLoader: couldn't find DSO to load: libv8executor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.myApp/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.myApp-YmzXmLHzJPnhwWqk0O3EtA==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/com.myApp-YmzXmLHzJPnhwWqk0O3EtA==/lib/arm64
     result: 0
    
    --------- beginning of crash
2023-10-23 20:23:38.070 30587-30675/com.myApp E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.myApp, PID: 30587
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libv8executor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.myApp/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.myApp-YmzXmLHzJPnhwWqk0O3EtA==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/com.myApp-YmzXmLHzJPnhwWqk0O3EtA==/lib/arm64
     result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:918)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582)
        at com.facebook.v8.reactexecutor.V8Executor.<clinit>(V8Executor.java:16)
        at com.facebook.v8.reactexecutor.V8ExecutorFactory.create(V8ExecutorFactory.java:20)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:919)
```
